# Generated by Django 3.1.3 on 2021-01-19 23:46

from django.db import migrations, models



class Migration(migrations.Migration):


    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='attributes_for_portfolio', to='exhibition.PortfolioAttributes', verbose_name='Аттрибуты фильтра'),
        ),
    ]
